-- Strategy Lab AI: run this entire file in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  starting_balance numeric not null default 1000000000000000000,
  current_balance numeric not null default 1000000000000000000,
  created_at timestamptz not null default now()
);

create table if not exists public.research_runs (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  market text not null,
  modes text[] not null default '{}',
  variations_requested integer not null,
  status text not null default 'queued',
  best_score numeric,
  starting_balance numeric not null default 1000000000000000000,
  current_balance numeric not null default 1000000000000000000,
  capital_events jsonb not null default '[]'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.strategies (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  run_id uuid references public.research_runs(id) on delete set null,
  symbol text not null,
  market text not null,
  name text not null,
  family text not null,
  parameters jsonb not null default '{}'::jsonb,
  source text not null default 'AI generated',
  approved boolean not null default false,
  score numeric not null default 0,
  metrics jsonb not null default '{}'::jsonb,
  trades jsonb not null default '[]'::jsonb,
  equity jsonb not null default '[]'::jsonb,
  explanation text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.run_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.research_runs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  level text not null default 'info',
  message text not null,
  progress numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.capital_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  run_id uuid references public.research_runs(id) on delete set null,
  event_type text not null,
  amount_before numeric not null,
  amount_after numeric not null,
  created_at timestamptz not null default now()
);

create index if not exists strategies_user_score_idx on public.strategies(user_id, approved, score desc);
create index if not exists strategies_user_created_idx on public.strategies(user_id, created_at desc);
create index if not exists runs_user_started_idx on public.research_runs(user_id, started_at desc);

alter table public.profiles enable row level security;
alter table public.research_runs enable row level security;
alter table public.strategies enable row level security;
alter table public.run_events enable row level security;
alter table public.capital_events enable row level security;

create policy "profiles own" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "runs own" on public.research_runs for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "strategies own" on public.strategies for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "events own" on public.run_events for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "capital own" on public.capital_events for all using (auth.uid()=user_id) with check (auth.uid()=user_id);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,email) values(new.id,new.email) on conflict(id) do nothing; return new; end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
