export const CURRENCIES: { code:string; label:string }[] = [
  { code:'USD', label:'USD — US Dollar' },
  { code:'EUR', label:'EUR — Euro' },
  { code:'GBP', label:'GBP — British Pound' },
  { code:'JPY', label:'JPY — Japanese Yen' },
  { code:'CAD', label:'CAD — Canadian Dollar' },
  { code:'AUD', label:'AUD — Australian Dollar' },
  { code:'CHF', label:'CHF — Swiss Franc' },
  { code:'CNY', label:'CNY — Chinese Yuan' },
  { code:'HKD', label:'HKD — Hong Kong Dollar' },
  { code:'SGD', label:'SGD — Singapore Dollar' },
  { code:'INR', label:'INR — Indian Rupee' },
  { code:'KRW', label:'KRW — South Korean Won' },
  { code:'TWD', label:'TWD — New Taiwan Dollar' },
  { code:'NZD', label:'NZD — New Zealand Dollar' },
  { code:'SEK', label:'SEK — Swedish Krona' },
  { code:'NOK', label:'NOK — Norwegian Krone' },
  { code:'DKK', label:'DKK — Danish Krone' },
  { code:'PLN', label:'PLN — Polish Zloty' },
  { code:'CZK', label:'CZK — Czech Koruna' },
  { code:'HUF', label:'HUF — Hungarian Forint' },
  { code:'RON', label:'RON — Romanian Leu' },
  { code:'ISK', label:'ISK — Icelandic Krona' },
  { code:'TRY', label:'TRY — Turkish Lira' },
  { code:'RUB', label:'RUB — Russian Ruble' },
  { code:'UAH', label:'UAH — Ukrainian Hryvnia' },
  { code:'ILS', label:'ILS — Israeli New Shekel' },
  { code:'AED', label:'AED — UAE Dirham' },
  { code:'SAR', label:'SAR — Saudi Riyal' },
  { code:'QAR', label:'QAR — Qatari Riyal' },
  { code:'KWD', label:'KWD — Kuwaiti Dinar' },
  { code:'BHD', label:'BHD — Bahraini Dinar' },
  { code:'OMR', label:'OMR — Omani Rial' },
  { code:'EGP', label:'EGP — Egyptian Pound' },
  { code:'ZAR', label:'ZAR — South African Rand' },
  { code:'NGN', label:'NGN — Nigerian Naira' },
  { code:'KES', label:'KES — Kenyan Shilling' },
  { code:'GHS', label:'GHS — Ghanaian Cedi' },
  { code:'MAD', label:'MAD — Moroccan Dirham' },
  { code:'BRL', label:'BRL — Brazilian Real' },
  { code:'MXN', label:'MXN — Mexican Peso' },
  { code:'ARS', label:'ARS — Argentine Peso' },
  { code:'CLP', label:'CLP — Chilean Peso' },
  { code:'COP', label:'COP — Colombian Peso' },
  { code:'PEN', label:'PEN — Peruvian Sol' },
  { code:'UYU', label:'UYU — Uruguayan Peso' },
  { code:'MYR', label:'MYR — Malaysian Ringgit' },
  { code:'THB', label:'THB — Thai Baht' },
  { code:'IDR', label:'IDR — Indonesian Rupiah' },
  { code:'PHP', label:'PHP — Philippine Peso' },
  { code:'VND', label:'VND — Vietnamese Dong' },
  { code:'PKR', label:'PKR — Pakistani Rupee' },
  { code:'BDT', label:'BDT — Bangladeshi Taka' },
  { code:'LKR', label:'LKR — Sri Lankan Rupee' },
]
