// Curated universe of liquid, real, tradeable US tickers the portfolio AI can select from.
// Real market data (price, momentum, volatility) is pulled live for every symbol here via
// /api/market — nothing about the price or performance data is fabricated. The "tags" below
// are only used to match a plain-language description to candidates before real data scores
// them; they are not investment advice.
export type UniverseEntry = { symbol:string; sector:string; tags:string[] }

export const PORTFOLIO_UNIVERSE:UniverseEntry[] = [
  {symbol:'AAPL',sector:'Technology',tags:['tech','largecap','growth','consumer']},
  {symbol:'MSFT',sector:'Technology',tags:['tech','largecap','growth','cloud','ai']},
  {symbol:'GOOGL',sector:'Technology',tags:['tech','largecap','growth','ai','advertising']},
  {symbol:'AMZN',sector:'Consumer Discretionary',tags:['tech','largecap','growth','consumer','ecommerce']},
  {symbol:'META',sector:'Technology',tags:['tech','largecap','growth','ai','advertising']},
  {symbol:'NVDA',sector:'Technology',tags:['tech','largecap','growth','ai','semiconductor']},
  {symbol:'AVGO',sector:'Technology',tags:['tech','semiconductor','dividend']},
  {symbol:'AMD',sector:'Technology',tags:['tech','semiconductor','growth']},
  {symbol:'CRM',sector:'Technology',tags:['tech','cloud','growth']},
  {symbol:'ORCL',sector:'Technology',tags:['tech','cloud','dividend']},
  {symbol:'ADBE',sector:'Technology',tags:['tech','cloud','growth']},
  {symbol:'INTC',sector:'Technology',tags:['tech','semiconductor','value']},
  {symbol:'CSCO',sector:'Technology',tags:['tech','dividend','value']},
  {symbol:'IBM',sector:'Technology',tags:['tech','dividend','value','ai']},
  {symbol:'NFLX',sector:'Communication Services',tags:['tech','growth','consumer','streaming']},
  {symbol:'DIS',sector:'Communication Services',tags:['consumer','media','value']},
  {symbol:'TSLA',sector:'Consumer Discretionary',tags:['growth','consumer','ev','tech']},
  {symbol:'F',sector:'Consumer Discretionary',tags:['value','dividend','ev','automotive']},
  {symbol:'GM',sector:'Consumer Discretionary',tags:['value','dividend','automotive']},
  {symbol:'HD',sector:'Consumer Discretionary',tags:['dividend','consumer','largecap']},
  {symbol:'NKE',sector:'Consumer Discretionary',tags:['consumer','dividend','growth']},
  {symbol:'SBUX',sector:'Consumer Discretionary',tags:['consumer','dividend']},
  {symbol:'MCD',sector:'Consumer Discretionary',tags:['dividend','consumer','defensive']},
  {symbol:'WMT',sector:'Consumer Staples',tags:['defensive','dividend','consumer','largecap']},
  {symbol:'COST',sector:'Consumer Staples',tags:['defensive','growth','consumer']},
  {symbol:'PG',sector:'Consumer Staples',tags:['defensive','dividend','consumer']},
  {symbol:'KO',sector:'Consumer Staples',tags:['defensive','dividend','consumer']},
  {symbol:'PEP',sector:'Consumer Staples',tags:['defensive','dividend','consumer']},
  {symbol:'PM',sector:'Consumer Staples',tags:['dividend','defensive']},
  {symbol:'JNJ',sector:'Healthcare',tags:['healthcare','dividend','defensive']},
  {symbol:'UNH',sector:'Healthcare',tags:['healthcare','largecap','growth']},
  {symbol:'PFE',sector:'Healthcare',tags:['healthcare','dividend','value']},
  {symbol:'LLY',sector:'Healthcare',tags:['healthcare','growth']},
  {symbol:'MRK',sector:'Healthcare',tags:['healthcare','dividend']},
  {symbol:'ABBV',sector:'Healthcare',tags:['healthcare','dividend']},
  {symbol:'TMO',sector:'Healthcare',tags:['healthcare','growth']},
  {symbol:'ABT',sector:'Healthcare',tags:['healthcare','dividend']},
  {symbol:'JPM',sector:'Financials',tags:['financials','dividend','largecap','value']},
  {symbol:'BAC',sector:'Financials',tags:['financials','dividend','value']},
  {symbol:'WFC',sector:'Financials',tags:['financials','dividend','value']},
  {symbol:'GS',sector:'Financials',tags:['financials','dividend']},
  {symbol:'MS',sector:'Financials',tags:['financials','dividend']},
  {symbol:'V',sector:'Financials',tags:['financials','growth','payments']},
  {symbol:'MA',sector:'Financials',tags:['financials','growth','payments']},
  {symbol:'AXP',sector:'Financials',tags:['financials','dividend','payments']},
  {symbol:'BRK-B',sector:'Financials',tags:['financials','value','defensive']},
  {symbol:'XOM',sector:'Energy',tags:['energy','dividend','value']},
  {symbol:'CVX',sector:'Energy',tags:['energy','dividend','value']},
  {symbol:'COP',sector:'Energy',tags:['energy','dividend']},
  {symbol:'SLB',sector:'Energy',tags:['energy','value']},
  {symbol:'BA',sector:'Industrials',tags:['industrials','growth','value']},
  {symbol:'CAT',sector:'Industrials',tags:['industrials','dividend']},
  {symbol:'GE',sector:'Industrials',tags:['industrials','growth']},
  {symbol:'HON',sector:'Industrials',tags:['industrials','dividend']},
  {symbol:'UPS',sector:'Industrials',tags:['industrials','dividend']},
  {symbol:'RTX',sector:'Industrials',tags:['industrials','dividend','defense']},
  {symbol:'LMT',sector:'Industrials',tags:['industrials','dividend','defense']},
  {symbol:'NOC',sector:'Industrials',tags:['industrials','dividend','defense']},
  {symbol:'LIN',sector:'Materials',tags:['materials','dividend']},
  {symbol:'NEM',sector:'Materials',tags:['materials','value']},
  {symbol:'NEE',sector:'Utilities',tags:['utilities','dividend','defensive']},
  {symbol:'DUK',sector:'Utilities',tags:['utilities','dividend','defensive']},
  {symbol:'SO',sector:'Utilities',tags:['utilities','dividend','defensive']},
  {symbol:'AMT',sector:'Real Estate',tags:['realestate','dividend','defensive']},
  {symbol:'PLD',sector:'Real Estate',tags:['realestate','dividend']},
  {symbol:'O',sector:'Real Estate',tags:['realestate','dividend','defensive']},
  {symbol:'SPY',sector:'Broad Market',tags:['index','diversified','defensive','largecap']},
  {symbol:'QQQ',sector:'Broad Market',tags:['index','tech','growth','diversified']},
  {symbol:'VTI',sector:'Broad Market',tags:['index','diversified','defensive']},
  {symbol:'SHOP',sector:'Technology',tags:['tech','growth','ecommerce']},
  {symbol:'UBER',sector:'Technology',tags:['tech','growth','consumer']},
  {symbol:'PYPL',sector:'Financials',tags:['tech','payments','growth']},
  {symbol:'SQ',sector:'Financials',tags:['tech','payments','growth','smallcap']},
  {symbol:'PLTR',sector:'Technology',tags:['tech','growth','ai','smallcap']},
  {symbol:'SNOW',sector:'Technology',tags:['tech','growth','cloud','smallcap']},
  {symbol:'COIN',sector:'Financials',tags:['tech','growth','crypto','smallcap']},
]
